"use strict"

let template = null;

/**
 * @function createWelcomeElement
 * @description
 * Creates and returns a DOM fragment containing the welcome screen UI,
 * displayed in the content area before the user submits their first query.
 * The element renders a logo and a configurable prompt heading, intended
 * to give the interface a warm, branded initial state.
 *
 * Implements the same template-caching pattern as `createThinkingElement`:
 * a module-scoped `<template>` node is created on the first call and
 * reused on subsequent calls, with each call returning an independent
 * clone. This avoids re-parsing the HTML string on every invocation.
 *
 * @param {string} [text="Where should we start?"]
 * The heading text rendered below the logo. Customise to change the
 * welcome prompt without altering the surrounding markup.
 *
 * @param {boolean} [reuseNode=true]
 * When `true`, the cached template is reused if one already exists. Set
 * to `false` to force a fresh template — required if `text` has changed
 * since the last call, as the cached node retains its original innerHTML.
 *
 * @returns {DocumentFragment}
 * A cloned document fragment containing:
 * ```html
 * <div id="welcome">
 *   <div>
 *     <img src="assets/icons/n-logo.svg" />
 *     <h1>{text}</h1>
 *   </div>
 * </div>
 * ```
 * Ready to be passed directly to `progressiveDisplay` or appended to a
 * container element.
 *
 * @example
 * progressiveDisplay(createWelcomeElement(), content, { delay: 0, fadeInDelay: 1000 });
 *
 * @example
 * // Force a fresh element with a custom prompt
 * progressiveDisplay(createWelcomeElement("What can I help you with?", false), content);
 *
 * @notes
 * - Changing `text` on a repeat call has no effect unless `reuseNode` is
 *   `false`, since the cached template retains its original innerHTML.
 * - The logo path (`assets/icons/n-logo.svg`) is hardcoded. If the asset
 *   path changes, the template must be regenerated by passing
 *   `reuseNode = false`.
 */
export const createWelcomeElement = (text = "Ready to land the job?", reuseNode = true) => (
  template && reuseNode || (
    (template = document.createElement("template")).innerHTML = 
    `<div id="welcome">
      <div>
        <img src="../assets/icons/logo.svg" />
        <h1>${text}</h1>
      </div>
    </div>`
  ),
  template.content.cloneNode(true)
);